import "./global.scss";
import { Roboto } from "next/font/google";
import { cn } from "~/utils/cn";
import { SSRProvider } from "~/components/providers/SSRProvider";
import { TRPCClientProvider } from "~/components/providers/TRPCProvider";

import { Header } from "~/components/Header";
import { CSRFProvider } from "../components/providers/CSRFProvider";
import { headers } from "next/headers";
const font = Roboto({ weight: ["300", "400", "700"], subsets: ["latin"] });

export const metadata = {
   title: "Next.js",
   description: "Generated by Next.js",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
   const csrfToken = headers().get("X-CSRF-Token") ?? null;
   return (
      <SSRProvider>
         <CSRFProvider csrfToken={csrfToken}>
            <html lang="en" suppressHydrationWarning>
               <body
                  className={cn(
                     "bg-zinc-900 text-white antialiased",
                     font.className
                  )}
                  suppressHydrationWarning
               >
                  <TRPCClientProvider>
                     <Header />
                     <div className="z-[500] mt-[var(--header-height)] w-full">
                        {children}
                     </div>
                  </TRPCClientProvider>
               </body>
            </html>
         </CSRFProvider>
      </SSRProvider>
   );
};

export default RootLayout;
